In [2]:
import torch
from torch import nn
import torch.nn.functional as F

In [6]:
class Network(nn.Module):
    def __init__(self):
        super().__init__()
        
        self.hidden1 = nn.Linear(1024, 512)
        self.hidden2 = nn.Linear(512, 128)
        
        self.output = nn.Linear(128, 7)
        
    def forward(self, x):
        x = F.leaky_relu(self.hidden1(x))
        x = F.leaky_relu(self.hidden2(x))
        
        x = F.softmax(self.output(x), dim=1)
        
        return x

In [7]:
model = Network()
model

Network(
  (hidden1): Linear(in_features=1024, out_features=512, bias=True)
  (hidden2): Linear(in_features=512, out_features=128, bias=True)
  (output): Linear(in_features=128, out_features=7, bias=True)
)

In [9]:
model.hidden1.weight

Parameter containing:
tensor([[ 0.0089, -0.0096,  0.0128,  ..., -0.0196, -0.0062, -0.0132],
        [-0.0239, -0.0261, -0.0204,  ..., -0.0287,  0.0142,  0.0093],
        [ 0.0203, -0.0120, -0.0228,  ..., -0.0183,  0.0253, -0.0129],
        ...,
        [ 0.0028,  0.0115,  0.0167,  ...,  0.0288, -0.0171, -0.0103],
        [-0.0168,  0.0061,  0.0100,  ...,  0.0167, -0.0301,  0.0049],
        [ 0.0049,  0.0210,  0.0036,  ...,  0.0244, -0.0294, -0.0270]],
       requires_grad=True)

In [12]:
model.output.bias

Parameter containing:
tensor([ 0.0274, -0.0191,  0.0733,  0.0757, -0.0206, -0.0423,  0.0113],
       requires_grad=True)

In [38]:
# 5 datapoints
features = torch.rand(5, 1024)
features

tensor([[0.7045, 0.9515, 0.9855,  ..., 0.4967, 0.6462, 0.5098],
        [0.5999, 0.8059, 0.3228,  ..., 0.3751, 0.5274, 0.8470],
        [0.5694, 0.4296, 0.3341,  ..., 0.8681, 0.7825, 0.9851],
        [0.4504, 0.6892, 0.1652,  ..., 0.5084, 0.7558, 0.2162],
        [0.1427, 0.2377, 0.1988,  ..., 0.1253, 0.8300, 0.5698]])

In [39]:
model.forward(features)

tensor([[0.1535, 0.1285, 0.1501, 0.1464, 0.1435, 0.1396, 0.1383],
        [0.1451, 0.1271, 0.1537, 0.1523, 0.1439, 0.1458, 0.1321],
        [0.1582, 0.1278, 0.1498, 0.1526, 0.1365, 0.1375, 0.1376],
        [0.1491, 0.1324, 0.1567, 0.1528, 0.1411, 0.1346, 0.1334],
        [0.1538, 0.1296, 0.1559, 0.1489, 0.1376, 0.1427, 0.1314]],
       grad_fn=<SoftmaxBackward>)