In [4]:
import torch

In [76]:
# Returns a tensor filled with random numbers from a standard normal distribution, size specified in bracket
features = torch.randn((1,5))
features

tensor([[-0.3803, -0.6900,  1.4096, -1.1689,  0.2777]])

In [77]:
# Same as above with size same as argument tensor
weights = torch.randn_like(features)
weights

tensor([[ 0.1247, -1.7340,  1.5053,  0.5381, -0.7217]])

In [78]:
bias = torch.randn((1,1))
bias

tensor([[0.9897]])

In [81]:
output = torch.sum(features*weights, 1) + bias
output

tensor([[3.4312]])

In [82]:
from torch import nn

In [87]:
# Activation Functions
sigmoid = nn.Sigmoid()
sigmoid(features)

tensor([[0.4060, 0.3340, 0.8037, 0.2370, 0.5690]])

In [91]:
softmax = nn.Softmax(dim=1)
softmax(features)

tensor([[0.0989, 0.0726, 0.5925, 0.0450, 0.1910]])

In [93]:
tanh = nn.Tanh()
tanh(features)

tensor([[-0.3630, -0.5980,  0.8874, -0.8239,  0.2708]])

In [94]:
relu = nn.ReLU()
relu(features)

tensor([[0.0000, 0.0000, 1.4096, 0.0000, 0.2777]])

In [96]:
leaky_relu = nn.LeakyReLU()
leaky_relu(features)

tensor([[-0.0038, -0.0069,  1.4096, -0.0117,  0.2777]])

In [97]:
elu = nn.ELU()
elu(features)

tensor([[-0.3164, -0.4984,  1.4096, -0.6893,  0.2777]])